app = "koma-m32o4g"
primary_region = "fra"

# Використовуємо Dockerfile в корені
[build]

[env]
# Значення можна перекривати через secrets, ці змінні лише як дефолт
REALM = "koma.local"
LISTEN_PORT = "3478"
MIN_PORT = "49160"
MAX_PORT = "49180"

# ---------- TCP (3478 і 443) -> внутрішній 3478 ----------
[[services]]
  protocol = "tcp"
  internal_port = 3478
  processes = ["app"]

  # зовнішній TCP 3478
  [[services.ports]]
    port = 3478

  # зовнішній TCP 443 (TURN over TCP через 443)
  [[services.ports]]
    port = 443

# ---------- UDP 3478 (STUN/TURN) ----------
[[services]]
  protocol = "udp"
  internal_port = 3478
  processes = ["app"]

  [[services.ports]]
    port = 3478

# ---------- UDP Relay range 49160–49180 ----------
[[services]]
  protocol = "udp"
  internal_port = 49160
  processes = ["app"]

  [[services.ports]]
    start_port = 49160
    end_port   = 49180
