app = "koma-m32o4g"
primary_region = "fra"

[build]

# 3478/UDP (STUN/TURN)
[[services]]
  protocol = "udp"
  internal_port = 3478
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 3478

# 3478/TCP (TURN over TCP)
[[services]]
  protocol = "tcp"
  internal_port = 3478
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 3478

# (необов’язково) 443/TCP → 3478 для суворих мереж (без TLS-термінації!)
[[services]]
  protocol = "tcp"
  internal_port = 3478
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 443
