app = "koma-m32o4g"
primary_region = "fra"

[env]
REALM = "koma.local"
LISTEN_PORT = "3478"
MIN_PORT = "49160"
MAX_PORT = "49180"
PUBLIC_IP4 = "66.241.124.113"

# UDP 3478
[[services]]
  processes = ["app"]
  protocol = "udp"
  internal_port = 3478
  [[services.ports]]
    port = 3478

# TCP 3478 (звичайний TURN over TCP)
[[services]]
  processes = ["app"]
  protocol = "tcp"
  internal_port = 3478
  [[services.ports]]
    port = 3478

# TCP 443 → всередині на 3478 (для випадків коли 3478 заблоковано)
[[services]]
  processes = ["app"]
  protocol = "tcp"
  internal_port = 3478
  [[services.ports]]
    port = 443

# Діапазон UDP-портів для медіа-релею
[[services]]
  processes = ["app"]
  protocol = "udp"
  internal_port = 49160
  [[services.ports]]
    start_port = 49160
    end_port   = 49180
