app = "koma-m32o4g"
primary_region = "fra"

[env]
REALM = "koma.local"
TURN_USER = "test"
TURN_PASS = "test123"
LISTEN_PORT = "3478"
MIN_PORT = "49160"
MAX_PORT = "49180"
PUBLIC_IP4 = "66.241.124.113"

[processes]
# Автоматичне визначення приватної IP перед запуском turnserver
app = "/bin/sh -lc 'PRIVATE_IP4=$(/sbin/ip -4 -o addr show dev eth0 | awk \"{print \\$4}\" | cut -d/ -f1 | head -n1); \
exec turnserver -n --log-file=stdout --simple-log \
  --realm ${REALM} \
  --lt-cred-mech --user ${TURN_USER}:${TURN_PASS} \
  --cli-password disabled-cli \
  --fingerprint \
  --listening-ip 0.0.0.0 \
  --external-ip ${PUBLIC_IP4}/$PRIVATE_IP4 \
  --listening-port ${LISTEN_PORT} \
  --no-tls --no-dtls \
  --min-port ${MIN_PORT} --max-port ${MAX_PORT} \
  --no-loopback-peers --no-multicast-peers'"

# === 3478/udp (STUN/TURN) ===
[[services]]
processes = ["app"]
protocol = "udp"
internal_port = 3478
  [[services.ports]]
  port = 3478

# === 3478/tcp (діагностика/фолбек) ===
[[services]]
processes = ["app"]
protocol = "tcp"
internal_port = 3478
  [[services.ports]]
  port = 3478

# === 443/tcp (TURN-TCP через 443 для мобільних/заблокованого UDP) ===
[[services]]
processes = ["app"]
protocol = "tcp"
internal_port = 3478
  [[services.ports]]
  port = 443

# === Діапазон relay-портів 49160–49180/udp (має збігатися з --min/--max) ===
[[services]]
processes = ["app"]
protocol = "udp"
internal_port = 49160
  [[services.ports]]
  start_port = 49160
  end_port   = 49180
