app = "koma-m32o4g"
primary_region = "fra"

[build]
  # Використовується Dockerfile з репозиторію

# --- TURN 3478/UDP ---
[[services]]
  protocol = "udp"
  internal_port = 3478
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 3478

# --- TURN 3478/TCP (коли UDP блокується) ---
[[services]]
  protocol = "tcp"
  internal_port = 3478
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 3478

# --- ДОДАТКОВО: TCP 443 -> 3478 (для суворих мереж, БЕЗ TLS-термінації) ---
[[services]]
  protocol = "tcp"
  internal_port = 3478
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 443

# --- UDP relay-порти coturn (49160–49180) ---
# TURN через TCP теж виділяє UDP-реле адреси, тому тут достатньо лише UDP-діапазону.
[[services]]
  protocol = "udp"
  internal_port = 49160
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49160

[[services]]
  protocol = "udp"
  internal_port = 49161
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49161

[[services]]
  protocol = "udp"
  internal_port = 49162
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49162

[[services]]
  protocol = "udp"
  internal_port = 49163
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49163

[[services]]
  protocol = "udp"
  internal_port = 49164
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49164

[[services]]
  protocol = "udp"
  internal_port = 49165
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49165

[[services]]
  protocol = "udp"
  internal_port = 49166
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49166

[[services]]
  protocol = "udp"
  internal_port = 49167
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49167

[[services]]
  protocol = "udp"
  internal_port = 49168
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49168

[[services]]
  protocol = "udp"
  internal_port = 49169
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49169

[[services]]
  protocol = "udp"
  internal_port = 49170
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49170

[[services]]
  protocol = "udp"
  internal_port = 49171
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49171

[[services]]
  protocol = "udp"
  internal_port = 49172
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49172

[[services]]
  protocol = "udp"
  internal_port = 49173
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49173

[[services]]
  protocol = "udp"
  internal_port = 49174
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49174

[[services]]
  protocol = "udp"
  internal_port = 49175
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49175

[[services]]
  protocol = "udp"
  internal_port = 49176
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49176

[[services]]
  protocol = "udp"
  internal_port = 49177
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49177

[[services]]
  protocol = "udp"
  internal_port = 49178
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49178

[[services]]
  protocol = "udp"
  internal_port = 49179
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49179

[[services]]
  protocol = "udp"
  internal_port = 49180
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  [[services.ports]]
    port = 49180
