app = "koma-turn"            # змінити на свою назву app у Fly
primary_region = "waw"       # або найближчий до тебе регіон

[env]
REALM = "koma.local"
TURN_USER = "test"
TURN_PASS = "test123"
LISTEN_PORT = "3478"
MIN_PORT = "49160"
MAX_PORT = "49180"

# UDP 3478
[[services]]
protocol = "udp"
internal_port = 3478
  [[services.ports]]
  port = 3478

# TCP 3478 (на випадок дуже жорстких мереж)
[[services]]
protocol = "tcp"
internal_port = 3478
  [[services.ports]]
  port = 3478

# UDP-діапазон для медіа (49160–49180)
[[services]]
protocol = "udp"
internal_port = 49160
  [[services.ports]]
  port_range = { start = 49160, end = 49180 }
