app = "koma-m32o4g"
primary_region = "fra"

[env]
REALM = "koma.local"
TURN_USER = "test"
TURN_PASS = "test123"
LISTEN_PORT = "3478"
MIN_PORT = "49160"
MAX_PORT = "49180"

# Публічна IPv4 (із `flyctl ips list`)
PUBLIC_IP4 = "66.241.124.113"
# Приватна IPv4 усередині ВМ (із `ip -4 addr`)
PRIVATE_IP4 = "172.19.12.178"

[processes]
# УВАГА: один рядок без переносів!
# Слухаємо на PRIVATE_IP4, релей працює через приватну адресу,
# а клієнтам віддаємо PUBLIC_IP4 завдяки --external-ip (public/private).
app = "turnserver -v -v -n --log-file=stdout --simple-log --realm ${REALM} --lt-cred-mech --user ${TURN_USER}:${TURN_PASS} --cli-password disabled-cli --fingerprint --listening-ip ${PRIVATE_IP4} --relay-ip ${PRIVATE_IP4} --external-ip ${PUBLIC_IP4}/${PRIVATE_IP4} --listening-port ${LISTEN_PORT} --no-tls --no-dtls --min-port ${MIN_PORT} --max-port ${MAX_PORT} --no-loopback-peers --no-multicast-peers"

# === 3478/udp (STUN/TURN) ===
[[services]]
processes = ["app"]
protocol = "udp"
internal_port = 3478
  [[services.ports]]
  port = 3478

# === 3478/tcp (TURN-TCP діагностика/фолбек) ===
[[services]]
processes = ["app"]
protocol = "tcp"
internal_port = 3478
  [[services.ports]]
  port = 3478
  handlers = []  # raw TCP, без TLS-термінації

# === 443/tcp (TURN-TCP через 443 для мобільних/заблокованого UDP) ===
# Публічний 443 → внутрішній 3478 того ж процесу coturn.
[[services]]
processes = ["app"]
protocol = "tcp"
internal_port = 3478
  [[services.ports]]
  port = 443
  handlers = []  # обов'язково без TLS-термінації

# === Діапазон relay-портів 49160–49180/udp (збігається з --min/--max) ===
[[services]]
processes = ["app"]
protocol = "udp"
internal_port = 49160
  [[services.ports]]
  start_port = 49160
  end_port   = 49180
